"""Add APIRequestLog and APIErrorLog

Revision ID: 0545169e0c1b
Revises: 915b7f670935
Create Date: 2023-03-22 18:37:27.572204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0545169e0c1b'
down_revision = '915b7f670935'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_log_error',
    sa.Column('error_id', sa.String(length=120), nullable=False),
    sa.Column('request_id', sa.String(length=120), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('error_id')
    )
    op.create_table('api_log_request',
    sa.Column('request_id', sa.String(length=120), nullable=False),
    sa.Column('request_method', sa.String(length=40), nullable=False),
    sa.Column('request_path', sa.String(length=240), nullable=False),
    sa.Column('request_query_params', sa.Text(), nullable=False),
    sa.Column('api_key', sa.String(length=120), nullable=True),
    sa.Column('user_cid', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_log_request')
    op.drop_table('api_log_error')
    # ### end Alembic commands ###
