"""Add request_date to APIRequestLog

Revision ID: 18bbb7b79b60
Revises: 0545169e0c1b
Create Date: 2023-03-22 19:45:41.390618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18bbb7b79b60'
down_revision = '0545169e0c1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_log_request', sa.Column('request_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_log_request', 'request_date')
    # ### end Alembic commands ###
